---
title: "e) Model community abundance"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{e) Model community abundance}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(avesdemazan)

# Model fitting
library(lme4)       # glmer() for glmm
library(glmmTMB)    # glmm with AR-1  
library(blme)       # bglmer (used?)

# Model evaluation
library(afex)       # functionall_fit()
library(multcomp)   
library(emmeans)
library(bbmle)      # aictab
library(arm)        # se.fit()

# Result visualization
library(ggplot2)    
library(ggstance)  
library(grid)
library(gridExtra)  

#  markdown etc
library(knitr)    
```



## Model TOTAL individuals captures 


```{r}
data(ecuador_tot)
```


```{r}
names(ecuador_tot)
head(ecuador_tot,10)
```


This shows total captures of species that are included in the GLMM, NOT total captures of ALL species
```{r}
ggplot(data = ecuador_tot,
        aes(y = N/tot_net_hours*1000,
            x = year,
            color = session)) +
  geom_point() +
  facet_wrap(~Location) + 
  geom_smooth(method = lm,se = F) + 
  theme_bw()
```


### glmer

```{r}
glm_fit <- glm(N ~ 1 + time_cts +   # Null
                     Location +                               # Location
                     session + 
                     time_cts*Location*session +                         # Continuous time variable
                     offset(log(tot_net_hours)),
                   family = poisson,
                   data = ecuador_tot)

# I haven't really thought about this modl
glmm_fit <- lme4::glmer(N ~ 1 + time_cts +   # Null
                     #Location +                               # Location
                     #(1|session) +
                     #(1|Location) +
                     (1|year) +
                     (time_cts|session:Location) + 
                     #ns(time_cts,3) +                         # Continuous time variable
                     offset(log(tot_net_hours)),
                   family = poisson,
                   data = ecuador_tot)
summary(glmm_fit)
```


### glmmTMB

this stucture is currently different from the glmer() vs above
```{r}


# Fit negative binomial
library(splines)
fit_nb2 <- glmmTMB(N ~ 1 + time_cts +   # Null
                     Location +                               # Location
                     session + 
                     #ns(time_cts,3) +                         # Continuous time variable
                     offset(log(tot_net_hours)),
                   family = poisson,
                   data = ecuador_tot)

summary(fit_nb2)
```




